In [5]:
import numpy as np
import matplotlib.pyplot as plt
import random as rnd
import scipy.special as sc
import pandas as pd
import statsmodels.api as sm
import scipy.stats as st
import math
import csv
from scipy.interpolate import interp1d
import matplotlib.ticker as mtick
import matplotlib.patches as mpatches
from scipy import stats

In [13]:
matrice=pd.read_csv('dataset/matrice_lombardia.csv',sep=',',decimal='.')
matrice.head()

,PROV_ORIG,ZONA_ORIG,PROV_DEST,ZONA_DEST,FASCIA_ORARIA,LAV_COND,LAV_PAX,LAV_MOTO,LAV_FERRO,LAV_GOMMA,...,AFF_PIEDI,AFF_ALTRO,RIT_COND,RIT_PAX,RIT_MOTO,RIT_FERRO,RIT_GOMMA,RIT_BICI,RIT_PIEDI,RIT_ALTRO
0,MI,OPERA,PV,DORNO,09:00-09:59,0.03,0.0,0.0,0.0,0.00,...,0.0,0.0,0.00,0.03,0.0,0.0,0.00,0.0,0.0,0.0
1,PV,SAN GENESIO ED UNITI,MI,ASSAGO,22:00-22:59,0.01,0.0,0.0,0.0,0.00,...,0.0,0.0,0.01,0.00,0.0,0.0,0.00,0.0,0.0,0.0
2,PV,SANTA CRISTINA E BISSONE,MI,LISCATE,14:00-14:59,0.04,0.0,0.0,0.0,0.00,...,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
3,PV,TORRE D'ARESE - VILLANTERIO,LO,MASSALENGO,08:00-08:59,0.97,0.0,0.0,0.0,0.12,...,0.0,0.0,0.02,0.00,0.0,0.0,0.01,0.0,0.0,0.0
4,CO,LOMAZZO,MI,GARBAGNATE MILANESE,04:00-04:59,0.06,0.0,0.0,0.0,0.00,...,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0

In [19]:
matrice_ferro=matrice[['PROV_ORIG','ZONA_ORIG',	'PROV_DEST','ZONA_DEST','LAV_FERRO']]
matrice_ferro=matrice_ferro[matrice_ferro['LAV_FERRO']!=0]
matrice_ferro

,PROV_ORIG,ZONA_ORIG,PROV_DEST,ZONA_DEST,LAV_FERRO
35,CR,SAN MARTINO DEL LAGO - SCANDOLARA RAVARA,MI,MILANO 6,0.01
38,BG,FILAGO,MI,MILANO 6,0.02
44,RE,REGGIO EMILIA,PV,STRADELLA,0.07
49,LO,SAN FIORANO,LO,CORNOVECCHIO - MALEO,0.02
55,MI,MILANO 5,MI,BUCCINASCO,0.01
...,...,...,...,...,...
8513175,MB,RONCO BRIANTINO,MB,MONZA 3,0.01
8513198,BS,COLOGNE,BG,TREVIGLIO,0.04
8513204,LC,OLGIATE MOLGORA,MI,MILANO 5,0.08
8513206,MI,MILANO 11,MI,MILANO 4,0.86
8513207,BS,CELLATICA,MI,MILANO 13,0.15